### ISSUE TITLE
Testing Details Missing

### ISSUE THREAD

**Issue by MandaliaBhavik** [GoodDollar/ReactNativeFaceTec#17]
Hi @johnsmith-gooddollar 
Actually, I was referring to your implementation for React Native and was excited to implement it in my project also.
I have tested successfully native Apps provided by the FaceTec SDK.
While Implementing in React Native I am missing some values for the testing purpose.
I have successfully initialized the SDK but was not able to establish the Session and get the
 **[Error: Session could not be started due to an unexpected issue during the network request.]**

Can you help me to provide it for testing purposes only?

Any help/guidance will be really appreciated.

Thanks in Advance.

**Comment by johnsmith-gooddollar** [comment]
@MandaliaBhavik **Session could not be started** means the app couldn't access API endpoint which starts session and obtains a token.

The issue happens this library is strictly designed to use with **our** app and with **our** backend (because FaceTec doesn't allows to use Facetec server from outside in production, so we're calling our backend and it then is calling FaceTec custom server).

The library is allowing to set custom server url (we using this to switch between dev/qa/prod server).
By default it's empty string so without our server configs you're trying to call localhost and getting the error.

To use this library in Your app you'd need to adjust native API calling FV endpoints:
- to use Your server's endpoint urls ('/verify/face/...'  are **our** endpoints, you need to change those urls)
- to adjust payload you're sending 
- to adjust response processing

So you need to fork this project and adjust the following files:
https://github.com/GoodDollar/ReactNativeFaceTec/blob/master/ios/API/FaceVerification.swift
https://github.com/GoodDollar/ReactNativeFaceTec/blob/master/android/src/main/java/org/gooddollar/facetec/api/FaceVerification.java
